Script started on Fri 06 Nov 2015 03:41:51 PM PST
[btaub001@hammer hw1]$ ./rshell
btaub001@hammer.cs.ucr.edu$echo print this#not this
print this
btaub001@hammer.cs.ucr.edu$ls #----
comment	 multi	pass  rshell  rshell.cpp  single
btaub001@hammer.cs.ucr.edu$mkdir test#not directory
btaub001@hammer.cs.ucr.edu$ls
comment	 multi	pass  rshell  rshell.cpp  single  test
btaub001@hammer.cs.ucr.edu$rmdir test#nmore comments
btaub001@hammer.cs.ucr.edu$ls
comment	 multi	pass  rshell  rshell.cpp  single
btaub001@hammer.cs.ucr.edu$exit
[btaub001@hammer hw1]$ exit
exit

Script done on Fri 06 Nov 2015 03:42:46 PM PST
